"""empty message

Revision ID: 42c6ad3c6133
Revises: 69da271238f3
Create Date: 2024-03-15 15:54:22.627480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c6ad3c6133'
down_revision = '69da271238f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_courses_student_id_students'), 'students', ['student_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_students_course_id_courses'), 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_students_course_id_courses'), type_='foreignkey')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses_student_id_students'), type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
