"""empty message

Revision ID: f106f5eacfbf
Revises: e418e8214158
Create Date: 2024-03-14 13:39:21.553828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f106f5eacfbf'
down_revision = 'e418e8214158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageAlt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('imageAlt')

    # ### end Alembic commands ###
